#!/usr/bin/env bash

set -e

PATH="$HOME/.asdf/bin:$PATH"

CONFIGS="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"


case "$(uname -a)" in 
    *cygwin*|*CYGWIN*)
        CONFIGS+=" cygwin.conf.yaml"
        ;;
    *Darwin*)
        echo "darwin"
        CONFIGS+=" darwin.conf.yaml"
        ;;
    Linux*Microsoft*)
       echo "WSL"
       CONFIGS+=" wsl.conf.yaml"
       ;; 
esac

for config in ${CONFIGS} ${@}; do 
    if [ -f $config ]; then
        PATH=${PATH} "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-asdf -c "${config}" 
    fi
done

