#!/usr/bin/env bash

set -e

CONFIGS="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"


case "$(uname)" in 
    *cygwin*|*CYGWIN*)
        CONFIGS+=" cygwin.conf.yaml"
        ;;
    *Darwin*)
        echo "darwin"
        CONFIGS+=" darwin.conf.yaml"
        ;;
esac

for config in ${CONFIGS} ${@}; do 
    if [ -f $config ]; then
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${config}" 
    fi
done

